public enum CH1SavePoints
{
	CH1_NO_SAVE,
	CH1_INK_MACHINE_REVEAL_COMPLETE,
	CH1_COLLECTABLE_COLLECT_ALL,
	CH1_COLLECTABLE_COMPLETE,
	CH1_THEATRE_START,
	CH1_THEATRE_COMPLETE,
	CH1_INK_MACHINE_START,
	CH1_INK_MACHINE_COMPLETE,
	CH1_BASEMENT_START,
	CH1_BASEMENT_COMPLETE
}
