public static class ObjectiveConstants
{
	public const string NEW_OBJECTIVE_HEADER = "OBJECTIVES/NEW_OBJECTIVE_HEADER";

	public const string CURRENT_OBJECTIVE_HEADER = "OBJECTIVES/CURRENT_OBJECTIVE_HEADER";

	public const string OBJECTIVE_FIND_A_NEW_EXIT = "OBJECTIVES/OBJECTIVE_FIND_A_NEW_EXIT";

	public const string CH1_OBJ_01 = "OBJECTIVES/CH1_OBJ_01";

	public const string CH1_OBJ_01_TIP = "OBJECTIVES/CH1_OBJ_01_TIP";

	public const string CH1_OBJ_02 = "OBJECTIVES/CH1_OBJ_02";

	public const string CH1_OBJ_02_TIP = "OBJECTIVES/CH1_OBJ_02_TIP";

	public const string CH1_OBJ_03 = "OBJECTIVES/CH1_OBJ_03";

	public const string CH1_OBJ_03_TIP = "OBJECTIVES/CH1_OBJ_03_TIP";

	public const string CH1_OBJ_04 = "OBJECTIVES/CH1_OBJ_04";

	public const string CH1_OBJ_04_TIP = "OBJECTIVES/CH1_OBJ_04_TIP";

	public const string CH1_OBJ_05 = "OBJECTIVES/CH1_OBJ_05";

	public const string CH1_OBJ_06 = "OBJECTIVES/CH1_OBJ_06";

	public const string CH1_OBJ_07 = "OBJECTIVES/CH1_OBJ_07";

	public const string CH1_OBJ_07_TIP = "OBJECTIVES/CH1_OBJ_07_TIP";

	public const string CH1_OBJ_08 = "OBJECTIVES/CH1_OBJ_08";

	public const string CH1_OBJ_08_TIP = "OBJECTIVES/CH1_OBJ_08_TIP";

	public const string CH2_OBJECTIVE_NEW_EXIT = "OBJECTIVES/CH2_OBJECTIVE_NEW_EXIT";

	public const string CH2_OBJECTIVE_NEW_EXIT_TIP = "OBJECTIVES/CH2_OBJECTIVE_NEW_EXIT_TIP";

	public const string CH2_OBJECTIVE_GATE = "OBJECTIVES/CH2_OBJECTIVE_GATE";

	public const string CH2_OBJECTIVE_GATE_TIP = "OBJECTIVES/CH2_OBJECTIVE_GATE_TIP";

	public const string CH2_OBJECTIVE_RAISE_GATE = "OBJECTIVES/CH2_OBJECTIVE_RAISE_GATE";

	public const string CH2_OBJECTIVE_RAISE_GATE_TIP = "OBJECTIVES/CH2_OBJECTIVE_RAISE_GATE_TIP";

	public const string CH2_OBJECTIVE_STAIRWELL = "OBJECTIVES/CH2_OBJECTIVE_STAIRWELL";

	public const string CH2_OBJECTIVE_STAIRWELL_TIP = "OBJECTIVES/CH2_OBJECTIVE_STAIRWELL_TIP";

	public const string CH2_OBJECTIVE_UNLOCK_CLOSET = "OBJECTIVES/CH2_OBJECTIVE_UNLOCK_CLOSET";

	public const string CH2_OBJECTIVE_UNLOCK_CLOSET_TIP = "OBJECTIVES/CH2_OBJECTIVE_UNLOCK_CLOSET_TIP";

	public const string CH2_OBJECTIVE_SANCTUARY = "OBJECTIVES/CH2_OBJECTIVE_SANCTUARY";

	public const string CH2_OBJECTIVE_SANCTUARY_TIP = "OBJECTIVES/CH2_OBJECTIVE_SANCTUARY_TIP";

	public const string CH2_OBJECTIVE_ENTER_SANCTUARY = "OBJECTIVES/CH2_OBJECTIVE_ENTER_SANCTUARY";

	public const string CH2_OBJECTIVE_SECOND_VALVE = "OBJECTIVES/CH2_OBJECTIVE_SECOND_VALVE";

	public const string CH2_OBJECTIVE_SAMMYS_OFFICE = "OBJECTIVES/CH2_OBJECTIVE_SAMMYS_OFFICE";

	public const string CH2_OBJECTIVE_TAKE_STAIRS = "OBJECTIVES/CH2_OBJECTIVE_TAKE_STAIRS";

	public const string CH2_OBJECTIVE_ESCAPE_BENDY = "OBJECTIVES/CH2_OBJECTIVE_ESCAPE_BENDY";

	public const string CH2_OBJECTIVE_ESCAPE_BENDY_TIP = "OBJECTIVES/CH2_OBJECTIVE_ESCAPE_BENDY_TIP";

	public const string CH3_OBJECTIVE_01 = "OBJECTIVES/CH3_OBJECTIVE_01";

	public const string CH3_OBJECTIVE_01_TIP = "OBJECTIVES/CH3_OBJECTIVE_01_TIP";

	public const string CH3_OBJECTIVE_02 = "OBJECTIVES/CH3_OBJECTIVE_02";

	public const string CH3_OBJECTIVE_02_TIP = "OBJECTIVES/CH3_OBJECTIVE_02_TIP";

	public const string CH3_OBJECTIVE_03 = "OBJECTIVES/CH3_OBJECTIVE_03";

	public const string CH3_OBJECTIVE_03_TIP = "OBJECTIVES/CH3_OBJECTIVE_03_TIP";

	public const string CH3_OBJECTIVE_04 = "OBJECTIVES/CH3_OBJECTIVE_04";

	public const string CH3_OBJECTIVE_05 = "OBJECTIVES/CH3_OBJECTIVE_05";

	public const string CH3_OBJECTIVE_05_TIP = "OBJECTIVES/CH3_OBJECTIVE_05_TIP";

	public const string CH3_OBJECTIVE_06 = "OBJECTIVES/CH3_OBJECTIVE_06";

	public const string CH3_OBJECTIVE_06_TIP = "OBJECTIVES/CH3_OBJECTIVE_06_TIP";

	public const string CH3_OBJECTIVE_07 = "OBJECTIVES/CH3_OBJECTIVE_07";

	public const string CH3_OBJECTIVE_07_TIP = "OBJECTIVES/CH3_OBJECTIVE_07_TIP";

	public const string CH3_OBJECTIVE_08 = "OBJECTIVES/CH3_OBJECTIVE_08";

	public const string CH3_OBJECTIVE_08_TIP = "OBJECTIVES/CH3_OBJECTIVE_08_TIP";

	public const string CH3_OBJECTIVE_09 = "OBJECTIVES/CH3_OBJECTIVE_09";

	public const string CH3_OBJECTIVE_09_TIP = "OBJECTIVES/CH3_OBJECTIVE_09_TIP";

	public const string CH3_OBJECTIVE_10 = "OBJECTIVES/CH3_OBJECTIVE_10";

	public const string CH3_OBJECTIVE_10_TIP = "OBJECTIVES/CH3_OBJECTIVE_10_TIP";

	public const string CH3_OBJECTIVE_11 = "OBJECTIVES/CH3_OBJECTIVE_11";

	public const string CH3_OBJECTIVE_11_TIP = "OBJECTIVES/CH3_OBJECTIVE_11_TIP";

	public const string CH3_OBJECTIVE_12 = "OBJECTIVES/CH3_OBJECTIVE_12";

	public const string CH3_OBJECTIVE_12_TIP = "OBJECTIVES/CH3_OBJECTIVE_12_TIP";

	public const string CH3_OBJECTIVE_14 = "OBJECTIVES/CH3_OBJECTIVE_14";

	public const string CH3_OBJECTIVE_14_TIP = "OBJECTIVES/CH3_OBJECTIVE_14_TIP";

	public const string CH3_OBJECTIVE_BORIS_PIPE = "OBJECTIVES/CH3_OBJECTIVE_BORIS_PIPE";

	public const string CH3_OBJECTIVE_BORIS_PIPE_TIP = "OBJECTIVES/CH3_OBJECTIVE_BORIS_PIPE_TIP";

	public const string CH3_OBJECTIVE_16 = "OBJECTIVES/CH3_OBJECTIVE_16";

	public const string CH3_OBJECTIVE_16_TIP = "OBJECTIVES/CH3_OBJECTIVE_16_TIP";

	public const string CH3_OBJECTIVE_17 = "OBJECTIVES/CH3_OBJECTIVE_17";

	public const string CH3_OBJECTIVE_17_TIP = "OBJECTIVES/CH3_OBJECTIVE_17_TIP";

	public const string CH3_OBJECTIVE_TASK_THICK_INK_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_THICK_INK_START";

	public const string CH3_OBJECTIVE_TASK_THICK_INK = "OBJECTIVES/CH3_OBJECTIVE_TASK_THICK_INK";

	public const string CH3_OBJECTIVE_TASK_THICK_INK_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_THICK_INK_TIP";

	public const string CH3_OBJECTIVE_TASK_THICK_INK_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_THICK_INK_COMPLETE_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_THICK_INK_COMPLETE_TIP";

	public const string CH3_OBJECTIVE_TASK_GEARS_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_GEARS_START";

	public const string CH3_OBJECTIVE_TASK_GEARS = "OBJECTIVES/CH3_OBJECTIVE_TASK_GEARS";

	public const string CH3_OBJECTIVE_TASK_GEARS_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_GEARS_TIP";

	public const string CH3_OBJECTIVE_TASK_GEARS_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_GEARS_COMPLETE_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_GEARS_COMPLETE_TIP";

	public const string CH3_OBJECTIVE_TASK_VALVE_CORES_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_VALVE_CORES_START";

	public const string CH3_OBJECTIVE_TASK_VALVE_CORES = "OBJECTIVES/CH3_OBJECTIVE_TASK_VALVE_CORES";

	public const string CH3_OBJECTIVE_TASK_VALVE_CORES_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_VALVE_CORES_TIP";

	public const string CH3_OBJECTIVE_TASK_VALVE_CORES_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_VALVE_CORES_COMPLETE_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_VALVE_CORES_COMPLETE_TIP";

	public const string CH3_OBJECTIVE_TASK_CUTOUT_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_CUTOUT_START";

	public const string CH3_OBJECTIVE_TASK_CUTOUT = "OBJECTIVES/CH3_OBJECTIVE_TASK_CUTOUT";

	public const string CH3_OBJECTIVE_TASK_CUTOUT_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_CUTOUT_TIP";

	public const string CH3_OBJECTIVE_TASK_CUTOUT_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_CUTOUT_COMPLETE_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_CUTOUT_COMPLETE_TIP";

	public const string CH3_OBJECTIVE_TASK_KILL_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_KILL_START";

	public const string CH3_OBJECTIVE_TASK_KILL_START_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_KILL_START_TIP";

	public const string CH3_OBJECTIVE_TASK_KILL_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_PROJECTIONIST_START = "OBJECTIVES/CH3_OBJECTIVE_TASK_PROJECTIONIST_START";

	public const string CH3_OBJECTIVE_TASK_PROJECTIONIST = "OBJECTIVES/CH3_OBJECTIVE_TASK_PROJECTIONIST";

	public const string CH3_OBJECTIVE_TASK_PROJECTIONIST_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_PROJECTIONIST_TIP";

	public const string CH3_OBJECTIVE_TASK_PROJECTIONIST_COMPLETE = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH3_OBJECTIVE_TASK_PROJECTIONIST_COMPLETE_TIP = "OBJECTIVES/CH3_OBJECTIVE_TASK_PROJECTIONIST_COMPLETE_TIP";

	public const string CH3_OBJECTIVE_TASK_RETURN_ALICE = "OBJECTIVES/CH3_OBJECTIVE_TASK_RETURN_ALICE";

	public const string CH3_OBJECTIVE_TASK_COMPLETE_A = "OBJECTIVES/CH3_OBJECTIVE_TASK_COMPLETE_A";

	public const string CH3_OBJECTIVE_TASK_COMPLETE_B = "OBJECTIVES/CH3_OBJECTIVE_TASK_COMPLETE_B";

	public const string CH3_OBJECTIVE_RETURN_TO_THE_ANGEL = "OBJECTIVES/CH3_OBJECTIVE_RETURN_TO_THE_ANGEL";

	public const string CH4_OBJECTIVE_RESCUE_BORIS = "OBJECTIVES/CH4_OBJECTIVE_RESCUE_BORIS";

	public const string CH4_OBJECTIVE_ENTER_THE_ARCHIVES = "OBJECTIVES/CH4_OBJECTIVE_ENTER_THE_ARCHIVES";

	public const string CH4_OBJECTIVE_ENTER_THE_ARCHIVES_TIP = "OBJECTIVES/CH4_OBJECTIVE_ENTER_THE_ARCHIVES_TIP";

	public const string CH4_OBJECTIVE_SECRET_PASSAGE = "OBJECTIVES/CH4_OBJECTIVE_SECRET_PASSAGE";

	public const string CH4_OBJECTIVE_ENTER_THE_DARKNESS = "OBJECTIVES/CH4_OBJECTIVE_ENTER_THE_DARKNESS";

	public const string CH4_OBJECTIVE_REPAIR_THE_BRIDGE = "OBJECTIVES/CH4_OBJECTIVE_REPAIR_THE_BRIDGE";

	public const string CH4_OBJECTIVE_HAUNTED_HOUSE = "OBJECTIVES/CH4_OBJECTIVE_HAUNTED_HOUSE";

	public const string CH4_OBJECTIVE_HAUNTED_HOUSE_TIP = "OBJECTIVES/CH4_OBJECTIVE_HAUNTED_HOUSE_TIP";

	public const string CH5_OBJECTIVE_DRAIN_THE_PASSAGE = "OBJECTIVES/CH5_OBJECTIVE_DRAIN_THE_PASSAGE";

	public const string CH5_OBJECTIVE_DRAIN_THE_PASSAGE_TIP = "OBJECTIVES/CH5_OBJECTIVE_DRAIN_THE_PASSAGE_TIP";

	public const string CH5_OBJECTIVE_ESCAPE_YOUR_PRISON = "OBJECTIVES/CH5_OBJECTIVE_ESCAPE_YOUR_PRISON";

	public const string CH5_OBJECTIVE_ESCAPE_YOUR_PRISON_TIP = "OBJECTIVES/CH5_OBJECTIVE_ESCAPE_YOUR_PRISON_TIP";

	public const string CH5_OBJECTIVE_LAUNCH_THE_BARGE = "OBJECTIVES/CH5_OBJECTIVE_LAUNCH_THE_BARGE";

	public const string CH5_OBJECTIVE_FOLLOW_THE_INK_RIVER = "OBJECTIVES/CH5_OBJECTIVE_FOLLOW_THE_INK_RIVER";

	public const string CH5_OBJECTIVE_FOLLOW_THE_INK_RIVER_TIP = "OBJECTIVES/CH5_OBJECTIVE_FOLLOW_THE_INK_RIVER_TIP";

	public const string CH5_OBJECTIVE_UNCLOG_THE_PADDLEWHEEL = "OBJECTIVES/CH5_OBJECTIVE_UNCLOG_THE_PADDLEWHEEL";

	public const string CH5_OBJECTIVE_UNCLOG_THE_PADDLEWHEEL_TIP = "OBJECTIVES/CH5_OBJECTIVE_UNCLOG_THE_PADDLEWHEEL_TIP";

	public const string CH5_OBJECTIVE_SEARCH_THE_VAULT = "OBJECTIVES/CH5_OBJECTIVE_SEARCH_THE_VAULT";

	public const string CH5_OBJECTIVE_ENTER_THE_MACHINE = "OBJECTIVES/CH5_OBJECTIVE_ENTER_THE_MACHINE";
}
