public static class SubtitleConstants
{
	public const string DIALOGUE_CHAPTER_ONE_01 = "DIACH1/DIA_CH1_HENRY_01";

	public const string DIALOGUE_CHAPTER_ONE_02 = "DIACH1/DIA_CH1_HENRY_02";

	public const string DIALOGUE_CHAPTER_ONE_03 = "DIACH1/DIA_CH1_HENRY_03";

	public const string DIALOGUE_CHAPTER_ONE_04 = "DIACH1/DIA_CH1_HENRY_04";

	public const string DIALOGUE_CHAPTER_ONE_05 = "DIACH1/DIA_CH1_HENRY_05";

	public const string DIALOGUE_CHAPTER_ONE_06 = "DIACH1/DIA_CH1_HENRY_06";

	public const string DIALOGUE_CHAPTER_ONE_07 = "DIACH1/DIA_CH1_HENRY_07";

	public const string DIALOGUE_CHAPTER_ONE_08 = "DIACH1/DIA_CH1_HENRY_08";

	public const string DIALOGUE_CHAPTER_ONE_09 = "DIACH1/DIA_CH1_HENRY_09";

	public const string DIALOGUE_CHAPTER_ONE_10 = "DIACH1/DIA_CH1_HENRY_10";

	public const string DIALOGUE_CHAPTER_ONE_11 = "DIACH1/DIA_CH1_HENRY_11";

	public const string DIALOGUE_CHAPTER_ONE_12 = "DIACH1/DIA_CH1_HENRY_12";

	public const string DIALOGUE_CHAPTER_ONE_13 = "DIACH1/DIA_CH1_HENRY_13";

	public const string DIALOGUE_CHAPTER_TWO_01A = "DIACH2/DIA_CH2_HENRY_01";

	public const string DIALOGUE_CHAPTER_TWO_01B = "DIACH2/DIA_CH2_HENRY_02";

	public const string DIALOGUE_CHAPTER_TWO_02 = "DIACH2/DIA_CH2_HENRY_03";

	public const string DIALOGUE_CHAPTER_TWO_03 = "DIACH2/DIA_CH2_HENRY_04";

	public const string DIALOGUE_CHAPTER_TWO_04 = "DIACH2/DIA_CH2_HENRY_05";

	public const string DIALOGUE_CHAPTER_TWO_05 = "DIACH2/DIA_CH2_HENRY_06";

	public const string DIA_CH2_HENRY_07 = "DIACH2/DIA_CH2_HENRY_07";

	public const string DIALOGUE_CHAPTER_TWO_06 = "DIACH2/DIA_CH2_HENRY_08";

	public const string DIALOGUE_CHAPTER_TWO_07 = "DIACH2/DIA_CH2_HENRY_09";

	public const string DIALOGUE_CHAPTER_TWO_08 = "DIACH2/DIA_CH2_HENRY_10";

	public const string DIA_CH2_HENRY_11 = "DIACH2/DIA_CH2_HENRY_11";

	public const string DIALOGUE_CHAPTER_TWO_12 = "DIACH2/DIA_CH2_HENRY_12";

	public const string DIALOGUE_CHAPTER_TWO_13 = "DIACH2/DIA_CH2_HENRY_13";

	public const string DIALOGUE_CHAPTER_TWO_09 = "DIACH2/DIA_CH2_HENRY_14";

	public const string DIALOGUE_CHAPTER_TWO_10 = "DIACH2/DIA_CH2_HENRY_15";

	public const string DIALOGUE_CHAPTER_TWO_11 = "DIACH2/DIA_CH2_HENRY_16";

	public static string[] DIALOGUE_CHAPTER_TWO_SAMMY_FINALE_MONOLOGUE = new string[11]
	{
		"DIACH2/DIA_CH2_SAMMY_MONOLOGUE_01", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_02", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_03", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_04", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_05", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_06", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_07", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_08", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_09", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_10",
		"DIACH2/DIA_CH2_SAMMY_MONOLOGUE_11"
	};

	public static string[] DIALOGUE_CHAPTER_TWO_SAMMY_FINALE_SPEAKER_MONOLOGUE = new string[7] { "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_01", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_02", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_03", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_04", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_05", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_06", "DIACH2/DIA_CH2_SAMMY_MONOLOGUE_SPEAKER_07" };

	public static string[] DIA_CH3_HENRY_NOT_GETTING_OUT = new string[2] { "DIACH3/DIA_CH3_HENRY_01", "DIACH3/DIA_CH3_HENRY_02" };

	public static string[] DIA_CH3_HENRY_HEY_BUDDY = new string[2] { "DIACH3/DIA_CH3_HENRY_03", "DIACH3/DIA_CH3_HENRY_04" };

	public const string DIALOGUE_CH3_HENRY_05 = "DIACH3/DIA_CH3_HENRY_05";

	public const string DIALOGUE_CH3_HENRY_06 = "DIACH3/DIA_CH3_HENRY_06";

	public const string DIALOGUE_CH3_HENRY_07 = "DIACH3/DIA_CH3_HENRY_07";

	public const string DIALOGUE_CH3_HENRY_08 = "DIACH3/DIA_CH3_HENRY_08";

	public static string[] DIA_CH3_HENRY_DID_YOU_HEAR_THAT = new string[2] { "DIACH3/DIA_CH3_HENRY_09", "DIACH3/DIA_CH3_HENRY_10" };

	public static string[] DIA_CH3_HENRY_DEAD_END = new string[2] { "DIACH3/DIA_CH3_HENRY_11", "DIACH3/DIA_CH3_HENRY_12" };

	public const string DIALOGUE_CH3_HENRY_13 = "DIACH3/DIA_CH3_HENRY_13";

	public static string[] DIA_CH3_HENRY_BLOCKING_THE_WAY = new string[2] { "DIACH3/DIA_CH3_HENRY_14", "DIACH3/DIA_CH3_HENRY_15" };

	public const string DIALOGUE_CH3_HENRY_20 = "DIACH3/DIA_CH3_HENRY_16";

	public const string DIALOGUE_CH3_HENRY_21 = "DIACH3/DIA_CH3_HENRY_17";

	public static string[] DIA_CH3_HENRY_BORIS_SCARE = new string[2] { "DIACH3/DIA_CH3_HENRY_18", "DIACH3/DIA_CH3_HENRY_19" };

	public const string DIALOGUE_CH3_HENRY_24 = "DIACH3/DIA_CH3_HENRY_20";

	public const string DIALOGUE_CH3_HENRY_25 = "DIACH3/DIA_CH3_HENRY_26";

	public const string DIALOGUE_CH3_HENRY_26 = "DIACH3/DIA_CH3_HENRY_27";

	public const string DIALOGUE_CH3_HENRY_27 = "DIACH3/DIA_CH3_HENRY_28";

	public const string DIALOGUE_CH3_HENRY_28 = "DIACH3/DIA_CH3_HENRY_29";

	public const string DIALOGUE_CH3_HENRY_29 = "DIACH3/DIA_CH3_HENRY_25";

	public const string DIALOG_CH3_HENRY_30 = "DIACH3/DIA_CH3_HENRY_30";

	public static string[] DIALOGUE_HENRY_SAVE = new string[5] { "Another day, another dollar.", "Punching in.", "I better get overtime for this.", "Always on time.", "Back to the old grind." };

	public static string[] DIALOGUE_CH4_HENRY_RESEARCH = new string[2] { "DIACH4/DIA_CH4_HENRY_RESEARCH_01", "DIACH4/DIA_CH4_HENRY_RESEARCH_02" };

	public static string[] DIALOGUE_CH4_HAUNTED_HOUSE = new string[2] { "DIACH4/DIA_CH4_HENRY_HAUNTED_HOUSE_01", "DIACH4/DIA_CH4_HENRY_HAUNTED_HOUSE_02" };

	public const string DIALOGUE_CH4_HENRY_01 = "DIACH4/DIA_CH4_HENRY_01";

	public const string DIALOGUE_CH4_HENRY_02 = "DIACH4/DIA_CH4_HENRY_02";

	public const string DIALOGUE_CH4_HENRY_03 = "DIACH4/DIA_CH4_HENRY_03";

	public static string DIA_CH4_HENRY_04 = "DIACH4/DIA_CH4_HENRY_04";

	public static string DIA_CH4_HENRY_05 = "DIACH4/DIA_CH4_HENRY_05";

	public static string DIA_CH4_HENRY_06 = "DIACH4/DIA_CH4_HENRY_06";

	public static string DIA_CH4_HENRY_07 = "DIACH4/DIA_CH4_HENRY_07";

	public static string DIA_CH4_HENRY_08 = "DIACH4/DIA_CH4_HENRY_08";

	public static string[] DIALOGUE_CH3_ALICE_REVEAL = new string[3] { "DIACH3/DIA_CH3_ALICE_REVEAL_01", "DIACH3/DIA_CH3_ALICE_REVEAL_02", "DIACH3/DIA_CH3_ALICE_REVEAL_03" };

	public static string[] DIALOGUE_CH3_ALICE_LIFT_01 = new string[5] { "DIACH3/DIA_CH3_ALICE_LIFT_01", "DIACH3/DIA_CH3_ALICE_LIFT_02", "DIACH3/DIA_CH3_ALICE_LIFT_03", "DIACH3/DIA_CH3_ALICE_LIFT_04", "DIACH3/DIA_CH3_ALICE_LIFT_05" };

	public static string[] DIALOGUE_CH3_ALICE_LIFT_02 = new string[2] { "DIACH3/DIA_CH3_ALICE_LIFT_END_01", "DIACH3/DIA_CH3_ALICE_LIFT_END_02" };

	public static string[] DIALOGUE_CH3_ALICE_DEAD_BODIES = new string[3] { "DIACH3/DIA_CH3_ALICE_BODIES_01", "DIACH3/DIA_CH3_ALICE_BODIES_02", "DIACH3/DIA_CH3_ALICE_BODIES_03" };

	public static string[] DIALOGUE_CH3_ALICE_MAIN_MONOLOGUE = new string[17]
	{
		"DIACH3/DIA_CH3_ALICE_MONOLOGUE_01", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_02", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_03", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_04", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_05", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_06", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_07", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_08", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_09", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_10",
		"DIACH3/DIA_CH3_ALICE_MONOLOGUE_11", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_12", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_13", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_14", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_15", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_16", "DIACH3/DIA_CH3_ALICE_MONOLOGUE_17"
	};

	public static string[] DIALOGUE_CH3_ALICE_BEGIN_TASKS = new string[7] { "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_01", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_02", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_03", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_04", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_05", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_06", "DIACH3/DIA_CH3_ALICE_TASKS_BEGIN_07" };

	public static string[] DIALOGUE_CH3_ALICE_INK_DEMON = new string[3] { "DIACH3/DIA_CH3_ALICE_INK_DEMON_01", "DIACH3/DIA_CH3_ALICE_INK_DEMON_02", "DIACH3/DIA_CH3_ALICE_INK_DEMON_03" };

	public const string DIALOGUE_CH3_ALICE_22 = "DIACH3/DIA_CH3_ALICE_01";

	public static string[] DIA_CH3_ALICE_GEAR_END = new string[2] { "DIACH3/DIA_CH3_ALICE_02", "DIACH3/DIA_CH3_ALICE_03" };

	public static string[] DIA_CH3_ALICE_THICK_INK_START = new string[5] { "DIACH3/DIA_CH3_ALICE_04", "DIACH3/DIA_CH3_ALICE_05", "DIACH3/DIA_CH3_ALICE_06", "DIACH3/DIA_CH3_ALICE_07", "DIACH3/DIA_CH3_ALICE_08" };

	public static string[] DIA_CH3_ALICE_THICK_INK_COMPLETE = new string[2] { "DIACH3/DIA_CH3_ALICE_09", "DIACH3/DIA_CH3_ALICE_10" };

	public static string[] DIA_CH3_ALICE_VALVES_START = new string[2] { "DIACH3/DIA_CH3_ALICE_11", "DIACH3/DIA_CH3_ALICE_12" };

	public const string DIALOGUE_CH3_ALICE_34 = "DIACH3/DIA_CH3_ALICE_13";

	public static string[] DIA_CH3_ALICE_CUTOUTS_START = new string[2] { "DIACH3/DIA_CH3_ALICE_14", "DIACH3/DIA_CH3_ALICE_15" };

	public static string[] DIA_CH3_ALICE_CUTOUTS_END = new string[2] { "DIACH3/DIA_CH3_ALICE_16", "DIACH3/DIA_CH3_ALICE_17" };

	public static string[] DIA_CH3_ALICE_PROJECTIONIST_START = new string[4] { "DIACH3/DIA_CH3_ALICE_18", "DIACH3/DIA_CH3_ALICE_19", "DIACH3/DIA_CH3_ALICE_20", "DIACH3/DIA_CH3_ALICE_21" };

	public const string DIALOGUE_CH3_ALICE_43 = "DIACH3/DIA_CH3_ALICE_22";

	public const string DIALOGUE_CH3_ALICE_44 = "DIACH3/DIA_CH3_ALICE_23";

	public const string DIALOGUE_CH3_ALICE_45 = "DIACH3/DIA_CH3_ALICE_24";

	public const string DIALOGUE_CH3_ALICE_44A = "DIACH3/DIA_CH3_ALICE_25";

	public const string DIALOGUE_CH3_ALICE_SPAWN = "DIACH3/DIA_CH3_ALICE_SPAWN";

	public static string[] DIALOGUE_CH3_ALICE_TASKS_COMPLETE = new string[4] { "DIACH3/DIA_CH3_ALICE_TASKS_COMPLETE_01", "DIACH3/DIA_CH3_ALICE_TASKS_COMPLETE_02", "DIACH3/DIA_CH3_ALICE_TASKS_COMPLETE_03", "DIACH3/DIA_CH3_ALICE_TASKS_COMPLETE_04" };

	public static string[] DIALOGUE_CH3_ALICE_FINALE_MONOLOGUE_A = new string[6] { "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_01", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_02", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_03", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_04", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_05", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_A_06" };

	public static string[] DIALOGUE_CH3_ALICE_FINALE_MONOLOGUE_B = new string[8] { "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_01", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_02", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_03", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_04", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_05", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_06", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_07", "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_B_08" };

	public static string[] DIALOGUE_CH3_ALICE_FINALE_MONOLOGUE_C = new string[1] { "DIACH3/DIA_CH3_ALICE_FINAL_MONOLOGUE_C" };

	public static string[] DIALOGUE_CH3_ALICE_TASK_VALVES_LIFT = new string[3] { "DIACH3/DIA_CH3_ALICE_TASKS_VALVES_LIFT_01", "DIACH3/DIA_CH3_ALICE_TASKS_VALVES_LIFT_02", "DIACH3/DIA_CH3_ALICE_TASKS_VALVES_LIFT_03" };

	public static string[] DIALOGUE_CH3_ALICE_TASK_GEARS_LIFT = new string[2] { "DIACH3/DIA_CH3_ALICE_TASKS_GEARS_LIFT_01", "DIACH3/DIA_CH3_ALICE_TASKS_GEARS_LIFT_02" };

	public static string[] DIALOGUE_CH3_ALICE_TASK_THICK_INK_LIFT = new string[3] { "DIACH3/DIA_CH3_ALICE_TASKS_THICK_INK_LIFT_01", "DIACH3/DIA_CH3_ALICE_TASKS_THICK_INK_LIFT_02", "DIACH3/DIA_CH3_ALICE_TASKS_THICK_INK_LIFT_03" };

	public static string[] DIA_CH3_ALICE_TASK_BUTCHER_GANG_START = new string[3] { "DIACH3/DIA_CH3_ALICE_26", "DIACH3/DIA_CH3_ALICE_27", "DIACH3/DIA_CH3_ALICE_28" };

	public const string DIALOGUE_CH3_ALICE_68 = "DIACH3/DIA_CH3_ALICE_29";

	public const string DIALOGUE_CH3_ALICE_71 = "DIACH3/DIA_CH3_ALICE_30";

	public const string DIALOGUE_CH3_ALICE_72 = "DIACH3/DIA_CH3_ALICE_31";

	public const string DIALOGUE_CH3_ALICE_79 = "DIACH3/DIA_CH3_ALICE_32";

	public const string DIALOGUE_CH4_ALICE_HAVING_FUN = "DIACH4/DIA_CH4_ALICE_HAVING_FUN";

	public static string[] DIALOGUE_CH4_ALICE_SPIRAL_STAIRS = new string[6] { "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_01", "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_02", "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_03", "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_04", "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_05", "DIACH4/DIA_CH4_ALICE_SPIRAL_STAIRS_06" };

	public static string[] DIALOBUE_CH4_ALICE_HAUNTED_HOUSE_START = new string[2] { "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_START_01", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_START_02" };

	public static string[] DIALOBUE_CH4_ALICE_HAUNTED_HOUSE_RIDE = new string[8] { "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_01", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_02", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_03", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_04", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_05", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_06", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_07", "DIACH4/DIA_CH4_ALICE_HAUNTED_HOUSE_RIDE_08" };

	public static string[] DIA_CH4_ALICE_BORIS_REVEAL = new string[5] { "DIACH4/DIA_CH4_ALICE_BORIS_REVEAL_01", "DIACH4/DIA_CH4_ALICE_BORIS_REVEAL_02", "DIACH4/DIA_CH4_ALICE_BORIS_REVEAL_03", "DIACH4/DIA_CH4_ALICE_BORIS_REVEAL_04", "DIACH4/DIA_CH4_ALICE_BORIS_REVEAL_05" };

	public static string[] DIA_CH4_ALICE_FINALE = new string[2] { "DIACH4/DIA_CH4_ALICE_BORIS_FINALE_01", "DIACH4/DIA_CH4_ALICE_BORIS_FINALE_02" };

	public static string[] DIA_CH4_BERT_REVEAL = new string[10] { "DIACH4/DIA_CH4_BERT_REVEAL_01", "DIACH4/DIA_CH4_BERT_REVEAL_02", "DIACH4/DIA_CH4_BERT_REVEAL_03", "DIACH4/DIA_CH4_BERT_REVEAL_04", "DIACH4/DIA_CH4_BERT_REVEAL_05", "DIACH4/DIA_CH4_BERT_REVEAL_06", "DIACH4/DIA_CH4_BERT_REVEAL_07", "DIACH4/DIA_CH4_BERT_REVEAL_08", "DIACH4/DIA_CH4_BERT_REVEAL_09", "DIACH4/DIA_CH4_BERT_REVEAL_10" };

	public static string[] DIA_CH5_OPENING_SCENE_01 = new string[17]
	{
		"DIACH5/DIA_CH5_OPENING_SCENE_01_01", "DIACH5/DIA_CH5_OPENING_SCENE_01_02", "DIACH5/DIA_CH5_OPENING_SCENE_01_03", "DIACH5/DIA_CH5_OPENING_SCENE_01_04", "DIACH5/DIA_CH5_OPENING_SCENE_01_05", "DIACH5/DIA_CH5_OPENING_SCENE_01_06", "DIACH5/DIA_CH5_OPENING_SCENE_01_07", "DIACH5/DIA_CH5_OPENING_SCENE_01_08", "DIACH5/DIA_CH5_OPENING_SCENE_01_09", "DIACH5/DIA_CH5_OPENING_SCENE_01_10",
		"DIACH5/DIA_CH5_OPENING_SCENE_01_11", "DIACH5/DIA_CH5_OPENING_SCENE_01_12", "DIACH5/DIA_CH5_OPENING_SCENE_01_13", "DIACH5/DIA_CH5_OPENING_SCENE_01_14", "DIACH5/DIA_CH5_OPENING_SCENE_01_15", "DIACH5/DIA_CH5_OPENING_SCENE_01_16", "DIACH5/DIA_CH5_OPENING_SCENE_01_17"
	};

	public static string[] DIA_CH5_OPENING_SCENE_02 = new string[6] { "DIACH5/DIA_CH5_OPENING_SCENE_02_01", "DIACH5/DIA_CH5_OPENING_SCENE_02_02", "DIACH5/DIA_CH5_OPENING_SCENE_02_03", "DIACH5/DIA_CH5_OPENING_SCENE_02_04", "DIACH5/DIA_CH5_OPENING_SCENE_02_05", "DIACH5/DIA_CH5_OPENING_SCENE_02_06" };

	public static string[] DIA_CH5_OPENING_SCENE_04 = new string[5] { "DIACH5/DIA_CH5_OPENING_SCENE_04_01", "DIACH5/DIA_CH5_OPENING_SCENE_04_02", "DIACH5/DIA_CH5_OPENING_SCENE_04_03", "DIACH5/DIA_CH5_OPENING_SCENE_04_04", "DIACH5/DIA_CH5_OPENING_SCENE_04_05" };

	public static string[] DIA_CH5_OPENING_SCENE_05 = new string[35]
	{
		"DIACH5/DIA_CH5_OPENING_SCENE_05_01", "DIACH5/DIA_CH5_OPENING_SCENE_05_02", "DIACH5/DIA_CH5_OPENING_SCENE_05_03", "DIACH5/DIA_CH5_OPENING_SCENE_05_04", "DIACH5/DIA_CH5_OPENING_SCENE_05_05", "DIACH5/DIA_CH5_OPENING_SCENE_05_06", "DIACH5/DIA_CH5_OPENING_SCENE_05_07", "DIACH5/DIA_CH5_OPENING_SCENE_05_08", "DIACH5/DIA_CH5_OPENING_SCENE_05_09", "DIACH5/DIA_CH5_OPENING_SCENE_05_10",
		"DIACH5/DIA_CH5_OPENING_SCENE_05_11", "DIACH5/DIA_CH5_OPENING_SCENE_05_12", "DIACH5/DIA_CH5_OPENING_SCENE_05_13", "DIACH5/DIA_CH5_OPENING_SCENE_05_14", "DIACH5/DIA_CH5_OPENING_SCENE_05_15", "DIACH5/DIA_CH5_OPENING_SCENE_05_16", "DIACH5/DIA_CH5_OPENING_SCENE_05_17", "DIACH5/DIA_CH5_OPENING_SCENE_05_18", "DIACH5/DIA_CH5_OPENING_SCENE_05_19", "DIACH5/DIA_CH5_OPENING_SCENE_05_20",
		"DIACH5/DIA_CH5_OPENING_SCENE_05_21", "DIACH5/DIA_CH5_OPENING_SCENE_05_22", "DIACH5/DIA_CH5_OPENING_SCENE_05_23", "DIACH5/DIA_CH5_OPENING_SCENE_05_24", "DIACH5/DIA_CH5_OPENING_SCENE_05_25", "DIACH5/DIA_CH5_OPENING_SCENE_05_26", "DIACH5/DIA_CH5_OPENING_SCENE_05_27", "DIACH5/DIA_CH5_OPENING_SCENE_05_28", "DIACH5/DIA_CH5_OPENING_SCENE_05_29", "DIACH5/DIA_CH5_OPENING_SCENE_05_30",
		"DIACH5/DIA_CH5_OPENING_SCENE_05_31", "DIACH5/DIA_CH5_OPENING_SCENE_05_32", "DIACH5/DIA_CH5_OPENING_SCENE_05_33", "DIACH5/DIA_CH5_OPENING_SCENE_05_34", "DIACH5/DIA_CH5_OPENING_SCENE_05_35"
	};

	public static string[] DIA_CH5_OPENING_SCENE_06 = new string[7] { "DIACH5/DIA_CH5_OPENING_SCENE_06_01", "DIACH5/DIA_CH5_OPENING_SCENE_06_02", "DIACH5/DIA_CH5_OPENING_SCENE_06_03", "DIACH5/DIA_CH5_OPENING_SCENE_06_04", "DIACH5/DIA_CH5_OPENING_SCENE_06_05", "DIACH5/DIA_CH5_OPENING_SCENE_06_06", "DIACH5/DIA_CH5_OPENING_SCENE_06_07" };

	public static string[] DIA_CH5_OPENING_SCENE_07 = new string[9] { "DIACH5/DIA_CH5_OPENING_SCENE_07_01", "DIACH5/DIA_CH5_OPENING_SCENE_07_02", "DIACH5/DIA_CH5_OPENING_SCENE_07_03", "DIACH5/DIA_CH5_OPENING_SCENE_07_04", "DIACH5/DIA_CH5_OPENING_SCENE_07_05", "DIACH5/DIA_CH5_OPENING_SCENE_07_06", "DIACH5/DIA_CH5_OPENING_SCENE_07_07", "DIACH5/DIA_CH5_OPENING_SCENE_07_08", "DIACH5/DIA_CH5_OPENING_SCENE_07_09" };

	public static string[] DIA_CH5_SAMMY_INTRO = new string[3] { "DIACH5/DIA_CH5_SAMMY_INTRO_01", "DIACH5/DIA_CH5_SAMMY_INTRO_02", "DIACH5/DIA_CH5_SAMMY_INTRO_03" };

	public static string[] DIA_CH5_SAMMY_DEATH = new string[9] { "DIACH5/DIA_CH5_SAMMY_DEATH_01", "DIACH5/DIA_CH5_SAMMY_DEATH_02", "DIACH5/DIA_CH5_SAMMY_DEATH_03", "DIACH5/DIA_CH5_SAMMY_DEATH_04", "DIACH5/DIA_CH5_SAMMY_DEATH_05", "DIACH5/DIA_CH5_SAMMY_DEATH_06", "DIACH5/DIA_CH5_SAMMY_DEATH_07", "DIACH5/DIA_CH5_SAMMY_DEATH_08", "DIACH5/DIA_CH5_SAMMY_DEATH_09" };

	public static string[] DIA_CH5_SAMMY_BATTLE = new string[5] { "DIACH5/DIA_CH5_SAMMY_BATTLE_01", "DIACH5/DIA_CH5_SAMMY_BATTLE_02", "DIACH5/DIA_CH5_SAMMY_BATTLE_03", "DIACH5/DIA_CH5_SAMMY_BATTLE_04", "DIACH5/DIA_CH5_SAMMY_BATTLE_05" };

	public static string[] DIA_CH5_ALISONA_BATTLE_INTRO = new string[7] { "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_01", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_02", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_03", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_04", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_05", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_06", "DIACH5/DIA_CH5_ALISONA_BATTLE_INTRO_07" };

	public static string[] DIA_CH5_ALISONA_BATTLE_ENDING = new string[4] { "DIACH5/DIA_CH5_ALISONA_BATTLE_ENDING_01", "DIACH5/DIA_CH5_ALISONA_BATTLE_ENDING_02", "DIACH5/DIA_CH5_ALISONA_BATTLE_ENDING_03", "DIACH5/DIA_CH5_ALISONA_BATTLE_ENDING_04" };

	public static string[] DIA_CH5_ALISONA_VAULT = new string[16]
	{
		"DIACH5/DIA_CH5_ALISONA_VAULT_01", "DIACH5/DIA_CH5_ALISONA_VAULT_02", "DIACH5/DIA_CH5_ALISONA_VAULT_03", "DIACH5/DIA_CH5_ALISONA_VAULT_04", "DIACH5/DIA_CH5_ALISONA_VAULT_05", "DIACH5/DIA_CH5_ALISONA_VAULT_06", "DIACH5/DIA_CH5_ALISONA_VAULT_07", "DIACH5/DIA_CH5_ALISONA_VAULT_08", "DIACH5/DIA_CH5_ALISONA_VAULT_09", "DIACH5/DIA_CH5_ALISONA_VAULT_10",
		"DIACH5/DIA_CH5_ALISONA_VAULT_11", "DIACH5/DIA_CH5_ALISONA_VAULT_12", "DIACH5/DIA_CH5_ALISONA_VAULT_13", "DIACH5/DIA_CH5_ALISONA_VAULT_14", "DIACH5/DIA_CH5_ALISONA_VAULT_15", "DIACH5/DIA_CH5_ALISONA_VAULT_16"
	};

	public static string[] DIA_CH5_ALISONA_GIANT_INK_MACHINE = new string[13]
	{
		"DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_01", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_02", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_03", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_04", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_05", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_06", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_07", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_08", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_09", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_10",
		"DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_11", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_12", "DIACH5/DIA_CH5_ALISONA_GIANT_INK_MACHINE_13"
	};

	public const string DIA_CH5_SAMMY_NO_MASK = "DIACH5/DIA_CH5_SAMMY_NO_MASK";

	public const string DIA_CH5_ALLISON_HENRY = "DIACH5/DIA_CH5_ALLISON_HENRY";

	public const string DIA_CH5_ALLISON_QUIET = "DIACH5/DIA_CH5_ALLISON_QUIET";

	public static string[] DIA_CH5_JOEY = new string[25]
	{
		"DIACH5/DIA_CH5_JOEY_01", "DIACH5/DIA_CH5_JOEY_02", "DIACH5/DIA_CH5_JOEY_03", "DIACH5/DIA_CH5_JOEY_04", "DIACH5/DIA_CH5_JOEY_05", "DIACH5/DIA_CH5_JOEY_06", "DIACH5/DIA_CH5_JOEY_07", "DIACH5/DIA_CH5_JOEY_08", "DIACH5/DIA_CH5_JOEY_09", "DIACH5/DIA_CH5_JOEY_10",
		"DIACH5/DIA_CH5_JOEY_11", "DIACH5/DIA_CH5_JOEY_12", "DIACH5/DIA_CH5_JOEY_13", "DIACH5/DIA_CH5_JOEY_14", "DIACH5/DIA_CH5_JOEY_15", "DIACH5/DIA_CH5_JOEY_16", "DIACH5/DIA_CH5_JOEY_17", "DIACH5/DIA_CH5_JOEY_18", "DIACH5/DIA_CH5_JOEY_19", "DIACH5/DIA_CH5_JOEY_20",
		"DIACH5/DIA_CH5_JOEY_21", "DIACH5/DIA_CH5_JOEY_22", "DIACH5/DIA_CH5_JOEY_23", "DIACH5/DIA_CH5_JOEY_24", "DIACH5/DIA_CH5_JOEY_25"
	};

	public const string DIA_CH5_HENRY_BUTCHER_GANG = "DIACH5/DIA_CH5_HENRY_BUTCHER_GANG";

	public const string DIA_CH5_HENRY_THE_END = "DIACH5/DIA_CH5_HENRY_THE_END";

	public const string DIA_CH5_HENRY_PADDLE_WHEEL = "DIACH5/DIA_CH5_HENRY_PADDLE_WHEEL";

	public const string DIA_CH5_HENRY_INTERESTING = "DIACH5/DIA_CH5_HENRY_INTERESTING";

	public const string DIA_CH5_HENRY_WEAPON = "DIACH5/DIA_CH5_HENRY_WEAPON";

	public static string[] DIA_CH5_JOEY_AUDIO_LOG = new string[11]
	{
		"DIACH5/DIA_CH5_JOEY_AUDIO_LOG_01", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_02", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_03", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_04", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_05", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_06", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_07", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_08", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_09", "DIACH5/DIA_CH5_JOEY_AUDIO_LOG_10",
		"DIACH5/DIA_CH5_JOEY_AUDIO_LOG_11"
	};
}
